package com.ablehealth.measure.mips.year2026;

import com.ablehealth.model.*
import com.ablehealth.payloads.*;
import com.ablehealth.results.*;
import com.ablehealth.enums.extendedmeaures.*;

global PatientResults controlSet;

declare Year2026Mips431Rate1G21967Org
end

declare Year2026Mips431Rate1G2196Group
    group: String
end

declare Year2026Mips431Rate1G2196Provider
    provider: String
end

declare Year2026Mips431Rate1G2197Org
end

declare Year2026Mips431Rate1G2197Group
    group: String
end

declare Year2026Mips431Rate1G2197Provider
    provider: String
end

/*
define "Denominator".org:
    (431shared."DenominatorRate1Rate3".org )DenOrg 
    ,
    if exists "Denominator".org
    return
    ExtendedMeasureResultV2(
        DenOrg 
        , 'Last Denominator Encounter' as name
        , display_date = start_date
        , calculated_record = false
        , population = denominator
        , option_id = all   
    ) 

*/
rule 'Year2026.Mips431Rate1.Denominator.Org'
when
    $program: Program(rules contains 'measure.Mips.2026.Mips431Rate1')
    $patient: Patient()
    Year2026Mips431SharedEncounterOrg($encounter: latestEncounter)
then
    insert(new EncounterDenominator($program, $encounter, "Year2026.Mips431Rate1", EncounterDenominatorType.ORG));
    String[] optionIds = new String[]{"G2196", "G2197", "M1164", "M1165", "G2199"};
    for (String optionId : optionIds) {
        controlSet.addPatientEMR($program, $patient, "Year2026.Mips431Rate1", "", "Last Denominator Encounter", optionId, PopulationEnum.denominator, $encounter, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $encounter.startDate.toString());
    }
end

/**
define "Denominator".group:
    (431shared."DenominatorRate1Rate3".group )DenGroup
    ,
    if exists "Denominator".group
    return
    ExtendedMeasureResultV2(
        DenGroup
        , 'Last Denominator Encounter' as name
        , display_date = start_date
        , calculated_record = false
        , population = denominator
        , option_id = all   
    )
*/
rule 'Year2026.Mips431Rate1.Denominator.Group'
when
    $program: Program(rules contains 'measure.Mips.2026.Mips431Rate1')
    $patient: Patient()
    Year2026Mips431SharedEncounterGroup($encounter: latestEncounter)
then
    insert(new EncounterDenominator($program, $encounter, "Year2026.Mips431Rate1", EncounterDenominatorType.GROUP));
    String[] optionIds = new String[]{"G2196", "G2197", "M1164", "M1165", "G2199"};
    for (String optionId : optionIds) {
        for(String group : $encounter.groupExternalIds) {
            controlSet.addPatientEMR($program, $patient, "Year2026.Mips431Rate1", group, "Last Denominator Encounter", optionId, PopulationEnum.denominator, $encounter, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $encounter.startDate.toString());
        }
    }
end

/**
define "Denominator".provider:
    (   431shared."DenominatorRate1Rate3".provider )DenProvider
    ,
    if exists "Denominator".provider
    return
    ExtendedMeasureResultV2(
        DenProvider
        , 'Last Denominator Encounter' as name
        , display_date = start_date
        , calculated_record = false
        , population = denominator
        , option_id = all   
    )
*/
rule 'Year2026.Mips431Rate1.Denominator.Provider'
when
    $program: Program(rules contains 'measure.Mips.2026.Mips431Rate1')
    $patient: Patient()
    Year2026Mips431SharedEncounterProvider($encounter: latestEncounter)
then
    insert(new EncounterDenominator($program, $encounter, "Year2026.Mips431Rate1", EncounterDenominatorType.PROVIDER));
    String[] optionIds = new String[]{"G2196", "G2197", "M1164", "M1165", "G2199"};
    for (String optionId : optionIds) {
        controlSet.addPatientEMR($program, $patient, "Year2026.Mips431Rate1", $encounter.providerExternalId, "Last Denominator Encounter", optionId, PopulationEnum.denominator, $encounter, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $encounter.startDate.toString());
    }
end

/*
define "Numerator Performance Met G2196".org:
   *
   * Option ID: G2196
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol User".org) AlcoholUserOrg
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholUserOrg
        , 'Most Recent Screening Indicates Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2196  
    )
*/
rule 'Year2026.Mips431Rate1.Success&EMR.G2196.Org'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.ORG)
    $patient: Patient()
    and not(
        exists Year2026Mips431Rate1G21967Org()
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholUser($patient, $mostRecentScreening, $result;)
    and not (exists queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $r;))
then
    insert(new Year2026Mips431Rate1G21967Org());
    controlSet.addPatientMeasureStatus($program, $patient, $measure, MeasureStatusValue.SUCCESS, "G2196");
    controlSet.addPatientEMR($program, $patient,  $measure, "", "Most Recent Screening Indicates Unhealthy Alcohol Use", "G2196", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/**
define "Numerator Performance Met G2196".group:
   *
   * Option ID: G2196
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol User".group) AlcoholUserGroup
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholUserGroup
        , 'Most Recent Screening Indicates Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2196  
    )
*/
rule 'Year2026.Mips431Rate1.Success.G2196&EMR.Group'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.GROUP)
    $patient: Patient()
    $groupExternalId: String() from $encounter.getGroupExternalIds()
    and not(
        exists Year2026Mips431Rate1G2196Group(group == $groupExternalId)
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholUser($patient, $mostRecentScreening, $result;)
    and not (exists queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $r;))
then
    insert(new Year2026Mips431Rate1G2196Group($encounter.groupExternalId));
    controlSet.addGroupPatientMeasureStatus($program, $patient, $groupExternalId, $measure, MeasureStatusValue.SUCCESS, "G2196");
    controlSet.addPatientEMR($program, $patient,  $measure, $groupExternalId, "Most Recent Screening Indicates Unhealthy Alcohol Use", "G2196", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/**
define "Numerator Performance Met G2196".provider:
   *
   * Option ID: G2196
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol User".provider) AlcoholUserProvider
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholUserProvider
        , 'Most Recent Screening Indicates Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2196  
    )
*/
rule 'Year2026.Mips431Rate1.Success&EMR.G2196.Provider'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.PROVIDER)
    $patient: Patient()
    and not(
        exists Year2026Mips431Rate1G2196Provider($encounter.providerExternalId == provider)
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholUser($patient, $mostRecentScreening, $result;)
    and not (exists queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $r;))
then
    insert(new Year2026Mips431Rate1G2196Provider($encounter.providerExternalId));
    controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId, $measure, MeasureStatusValue.SUCCESS, "G2196");
    controlSet.addPatientEMR($program, $patient,  $measure, $encounter.providerExternalId, "Most Recent Screening Indicates Unhealthy Alcohol Use", "G2196", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/*
define "Numerator Performance Met G2197".org:
   *
   * Option ID: G2197
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol Non User".org) AlcoholNonUserOrg
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholNonUserOrg
        , 'Most Recent Screening Does Not Indicate Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2197  
    )
*/
rule 'Year2026.Mips431Rate1.Success&EMR.G2197.Org'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.ORG)
    $patient: Patient()
    and not(
        exists Year2026Mips431Rate1G2197Org()
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $result;)
then
    insert(new Year2026Mips431Rate1G2197Org());
    controlSet.addPatientMeasureStatus($program, $patient, $measure, MeasureStatusValue.SUCCESS, "G2197");
    controlSet.addPatientEMR($program, $patient,  $measure, "", "Most Recent Screening Does Not Indicate Unhealthy Alcohol Use", "G2197", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/**
define "Numerator Performance Met G2197".group:
   *
   * Option ID: G2197
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol Non User".group) AlcoholNonUserGroup
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholNonUserGroup
        , 'Most Recent Screening Does Not Indicate Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2197  
    )
*/
rule 'Year2026.Mips431Rate1.Success&EMR.G2197.Group'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.GROUP)
    $patient: Patient()
    $groupExternalId: String() from $encounter.getGroupExternalIds()
    and not(
        exists Year2026Mips431Rate1G2197Group($groupExternalId == group)
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $result;)
then
    insert(new Year2026Mips431Rate1G2197Group($encounter.groupExternalId));
    controlSet.addGroupPatientMeasureStatus($program, $patient, $groupExternalId, $measure, MeasureStatusValue.SUCCESS, "G2197");
    controlSet.addPatientEMR($program, $patient,  $measure, $groupExternalId, "Most Recent Screening Does Not Indicate Unhealthy Alcohol Use", "G2197", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/**
define "Numerator Performance Met G2197.provider:
   *
   * Option ID: G2197
   *
    (431shared."Most Recent Alcohol Screening Indicates Alcohol Non User".provider) AlcoholNonUserProvider
    ,
    return
    ExtendedMeasureResultV2(
        AlcoholNonUserProvider
        , 'Most Recent Screening Does Not Indicate Unhealthy Alcohol Use' as name
        , display_date = start_date
        , calculated_record = false
        , population = Numerator Performance Met
        , option_id = G2197  
    )
*/
rule 'Year2026.Mips431Rate1.Success&EMR.G2197.Provider'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.PROVIDER)
    $patient: Patient()
    and not(
        exists Year2026Mips431Rate1G2197Provider($encounter.providerExternalId == provider)
    )
    and queryYear2026Mips431SharedMostRecentScreening($encounter, $mostRecentScreening;)
    and queryYear2026Mips431SharedMostRecentAlcoholScreeningIndicatesAlcoholNonUser($patient, $mostRecentScreening, $result;)
then
    insert(new Year2026Mips431Rate1G2197Provider($encounter.providerExternalId));
    controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId, $measure, MeasureStatusValue.SUCCESS, "G2197");
    controlSet.addPatientEMR($program, $patient,  $measure, $encounter.providerExternalId, "Most Recent Screening Does Not Indicate Unhealthy Alcohol Use", "G2197", PopulationEnum.numerator_performance_met, $result, SupplementalInfoEnum.DISPLAY_DATE.displayName(), $result.startDate.toString());
end

/*
define "Numerator Performance Not Met G2199".org:
   *
   * Option ID: G2199
   *
  "Denominator".org
   and not "Numerator Performance Met G2196"
   and not "Numerator Performance Met G2197"
   and not "Denominator Exclusion M1165"
   and not "Denominator Exclusion M1164"
*/
rule 'Year2026.Mips431Rate1.Gap.G2199.Org'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.ORG)
    $patient: Patient()
then
    controlSet.addPatientMeasureStatus($program, $patient, $measure, MeasureStatusValue.GAP, "G2199");
end

/**
define "Numerator Performance Not Met G2199".group:
   *
   * Option ID: G2199
   *
  "Denominator".group
   and not "Numerator Performance Met G2196"
   and not "Numerator Performance Met G2197"
   and not "Denominator Exclusion M1165"
   and not "Denominator Exclusion M1164"
*/
rule 'Year2026.Mips431Rate1.Gap.G2199.Group'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.GROUP)
    $patient: Patient()
then
    for(String group: $encounter.groupExternalIds) {
        controlSet.addGroupPatientMeasureStatus($program, $patient, group, $measure, MeasureStatusValue.GAP, "G2199");
    }
end

/**
define "Numerator Performance Not Met G2199".provider:
   *
   * Option ID: G2199
   *
  "Denominator".provider
   and not "Numerator Performance Met G2196"
   and not "Numerator Performance Met G2197"
   and not "Denominator Exclusion M1165"
   and not "Denominator Exclusion M1164"
*/
rule 'Year2026.Mips431Rate1.Gap.G2199.Provider'
when
    EncounterDenominator($program: program, $encounter: clinicalActivity, $measure: measure, measure == 'Year2026.Mips431Rate1', type == EncounterDenominatorType.PROVIDER)
    $patient: Patient()
then
    controlSet.addProviderPatientMeasureStatus($program, $patient, $encounter.providerExternalId, $measure, MeasureStatusValue.GAP, "G2199");
end
